// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "Gui.h"
#include "logic.h"
#include <FL/Fl_Text_Buffer.h>

void Gui::cb_inputTime_i(Fl_Input*, void*) {
  onInputTimeChange();
}
void Gui::cb_inputTime(Fl_Input* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_inputTime_i(o,v);
}

void Gui::cb_inputTitle_i(Fl_Input*, void*) {
  onInputTitleChange();
}
void Gui::cb_inputTitle(Fl_Input* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_inputTitle_i(o,v);
}

Fl_Double_Window* Gui::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(533, 382, "lblog");
    w = o;
    o->user_data((void*)(this));
    { inputTime = new Fl_Input(56, 10, 279, 24, "time:");
      inputTime->callback((Fl_Callback*)cb_inputTime);
    } // Fl_Input* inputTime
    { inputTitle = new Fl_Input(56, 42, 279, 24, "title:");
      inputTitle->callback((Fl_Callback*)cb_inputTitle);
    } // Fl_Input* inputTitle
    { outputSubdir = new Fl_Output(56, 74, 279, 28, "subdir:");
      outputSubdir->color(FL_DARK1);
    } // Fl_Output* outputSubdir
    { displayLog = new Fl_Text_Display(4, 276, 521, 101);
      displayLog->color(FL_FOREGROUND_COLOR);
      displayLog->textcolor(FL_BACKGROUND2_COLOR);
    } // Fl_Text_Display* displayLog
    { Fl_Browser_Dnd* o = outputAttachments = new Fl_Browser_Dnd(4, 166, 521, 104, "attachments:");
      outputAttachments->box(FL_NO_BOX);
      outputAttachments->color(FL_BACKGROUND2_COLOR);
      outputAttachments->selection_color(FL_SELECTION_COLOR);
      outputAttachments->labeltype(FL_NORMAL_LABEL);
      outputAttachments->labelfont(0);
      outputAttachments->labelsize(14);
      outputAttachments->labelcolor(FL_FOREGROUND_COLOR);
      outputAttachments->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      outputAttachments->when(FL_WHEN_RELEASE_ALWAYS);
      o->type(FL_HOLD_BROWSER);
      o->callback(onBrowserClick);
    } // Fl_Browser_Dnd* outputAttachments
    o->end();
  } // Fl_Double_Window* o
  return w;
}

int main(int argc, char **argv) {
  Gui *gui = new Gui();
  Fl_Double_Window *w = gui->make_window();
  w->show();
  onGuiStart(gui);
  printf("Hello, World!\n");
  return Fl::run();
}
