// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef Gui_h
#define Gui_h
#include <FL/Fl.H>
#include "Fl_Browser_Dnd.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Browser.H>
#include <FL/Fl_Button.H>

class Gui {
public:
  Fl_Double_Window* make_window();
  Fl_Input *inputTime;
private:
  inline void cb_inputTime_i(Fl_Input*, void*);
  static void cb_inputTime(Fl_Input*, void*);
public:
  Fl_Input *inputTitle;
private:
  inline void cb_inputTitle_i(Fl_Input*, void*);
  static void cb_inputTitle(Fl_Input*, void*);
public:
  Fl_Input *inputTags;
  Fl_Browser *displayLog;
  Fl_Browser_Dnd *browserAttachments;
private:
  inline void cb_remove_i(Fl_Button*, void*);
  static void cb_remove(Fl_Button*, void*);
  inline void cb_64x64_i(Fl_Button*, void*);
  static void cb_64x64(Fl_Button*, void*);
  inline void cb_128x128_i(Fl_Button*, void*);
  static void cb_128x128(Fl_Button*, void*);
  inline void cb_x64_i(Fl_Button*, void*);
  static void cb_x64(Fl_Button*, void*);
  inline void cb_x128_i(Fl_Button*, void*);
  static void cb_x128(Fl_Button*, void*);
  inline void cb_add_i(Fl_Button*, void*);
  static void cb_add(Fl_Button*, void*);
};
#endif
