// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef Gui_h
#define Gui_h
#include <FL/Fl.H>
#include "Fl_Output_Dnd.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Text_Display.H>

class Gui {
public:
  Fl_Double_Window* make_window();
  Fl_Input *inputTime;
private:
  inline void cb_inputTime_i(Fl_Input*, void*);
  static void cb_inputTime(Fl_Input*, void*);
public:
  Fl_Input *inputTitle;
private:
  inline void cb_inputTitle_i(Fl_Input*, void*);
  static void cb_inputTitle(Fl_Input*, void*);
public:
  Fl_Output *outputSubdir;
  Fl_Text_Display *displayLog;
  Fl_Output_Dnd *outputAttachments;
};
#endif
